-- CreateTable
CREATE TABLE "Team" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Phone" TEXT NOT NULL,
    "Note" TEXT NOT NULL,
    "Status" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "UserName" TEXT NOT NULL,
    "PassWord" TEXT NOT NULL,
    "Role" INTEGER NOT NULL DEFAULT 0,
    "Status" INTEGER NOT NULL DEFAULT 0,
    "Team_Id" INTEGER NOT NULL,
    CONSTRAINT "User_Team_Id_fkey" FOREIGN KEY ("Team_Id") REFERENCES "Team" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Reagent" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Specifications" TEXT NOT NULL,
    "Price" INTEGER NOT NULL DEFAULT 0,
    "StorageCondition" TEXT NOT NULL,
    "Manufacturer" TEXT NOT NULL,
    "Note" TEXT NOT NULL,
    "WarnNumber" INTEGER NOT NULL DEFAULT 0,
    "WarnDays" INTEGER NOT NULL DEFAULT 0,
    "CreateTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TeamId" INTEGER NOT NULL,
    "Status" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "Reagent_TeamId_fkey" FOREIGN KEY ("TeamId") REFERENCES "Team" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Lot" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "ReagentId" INTEGER NOT NULL,
    "ExpirationDate" DATETIME NOT NULL,
    "Status" INTEGER NOT NULL DEFAULT 0,
    "TeamId" INTEGER NOT NULL,
    CONSTRAINT "Lot_ReagentId_fkey" FOREIGN KEY ("ReagentId") REFERENCES "Reagent" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Lot_TeamId_fkey" FOREIGN KEY ("TeamId") REFERENCES "Team" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Operation" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ReagentId" INTEGER NOT NULL,
    "LotId" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "TeamId" INTEGER NOT NULL,
    "CreateTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BarcodeNumber" TEXT NOT NULL,
    "Action" INTEGER NOT NULL,
    "Note" TEXT NOT NULL,
    "Status" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "Operation_ReagentId_fkey" FOREIGN KEY ("ReagentId") REFERENCES "Reagent" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Operation_LotId_fkey" FOREIGN KEY ("LotId") REFERENCES "Lot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Operation_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Operation_TeamId_fkey" FOREIGN KEY ("TeamId") REFERENCES "Team" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Inventory" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ReagentId" INTEGER NOT NULL,
    "LotId" INTEGER NOT NULL,
    "TeamId" INTEGER NOT NULL,
    "Number" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "Inventory_ReagentId_fkey" FOREIGN KEY ("ReagentId") REFERENCES "Reagent" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Inventory_LotId_fkey" FOREIGN KEY ("LotId") REFERENCES "Lot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Inventory_TeamId_fkey" FOREIGN KEY ("TeamId") REFERENCES "Team" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
