/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action_select: typeof import('./src/components/action_select.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    Home: typeof import('./src/components/home.vue')['default']
    Homebar: typeof import('./src/components/homebar.vue')['default']
    Inbound: typeof import('./src/components/inbound.vue')['default']
    Location: typeof import('./src/components/location.vue')['default']
    Lot: typeof import('./src/components/lot.vue')['default']
    Messagebox: typeof import('./src/components/messagebox.vue')['default']
    Operation: typeof import('./src/components/operation.vue')['default']
    Outbound: typeof import('./src/components/outbound.vue')['default']
    Print: typeof import('./src/components/print.vue')['default']
    Reagent: typeof import('./src/components/reagent.vue')['default']
    Reagentlot_select: typeof import('./src/components/reagentlot_select.vue')['default']
    Reagentlot_select_test: typeof import('./src/components/reagentlot_select_test.vue')['default']
    Role_select: typeof import('./src/components/role_select.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensorRecord: typeof import('./src/components/sensorRecord.vue')['default']
    Signin: typeof import('./src/components/signin.vue')['default']
    Signout: typeof import('./src/components/signout.vue')['default']
    Statistics: typeof import('./src/components/statistics.vue')['default']
    Statistics_chart: typeof import('./src/components/statistics_chart.vue')['default']
    Team: typeof import('./src/components/team.vue')['default']
    Team_select: typeof import('./src/components/team_select.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
  }
}
