name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './vue/package-lock.json'
    
    - name: Clean install
      working-directory: ./vue
      run: npm install
    
    - name: Build
      working-directory: ./vue
      run: npm run build --if-present
    
    - name: Test
      working-directory: ./vue
      run: npm test
